# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-21 17:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('min_name', models.CharField(max_length=2)),
                ('image', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('idiom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='page.Idiom')),
                ('greeting', models.CharField(max_length=50)),
                ('info', models.TextField()),
                ('btn_try', models.CharField(max_length=10)),
                ('complete_registration', models.CharField(max_length=50)),
                ('message_complete_registration', models.CharField(max_length=255)),
                ('save_data', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Compiler',
            fields=[
                ('idiom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='page.Idiom')),
                ('info', models.TextField()),
                ('run', models.CharField(max_length=20)),
                ('save_pc', models.CharField(max_length=30)),
                ('save_db', models.CharField(max_length=30)),
                ('compilation_log', models.CharField(max_length=40)),
                ('execution_result', models.CharField(max_length=40)),
                ('go', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('idiom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='page.Idiom')),
                ('name', models.CharField(max_length=70)),
                ('home', models.CharField(max_length=20)),
                ('greeting', models.CharField(max_length=50)),
                ('min_info', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('sign_up', models.CharField(max_length=30)),
                ('login', models.CharField(max_length=30)),
                ('community', models.CharField(max_length=30)),
                ('compiler', models.CharField(max_length=30)),
                ('profile', models.CharField(max_length=30)),
                ('logout', models.CharField(max_length=30)),
                ('my_codes', models.CharField(max_length=30)),
                ('charts', models.CharField(max_length=50)),
                ('chart1_title', models.CharField(max_length=80)),
                ('chart2_title', models.CharField(max_length=80)),
                ('chart3_title', models.CharField(default='No hay titulo', max_length=80)),
                ('chart4_title', models.CharField(default='No hay titulo', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('idiom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='page.Idiom')),
                ('n_codes', models.CharField(max_length=20)),
                ('personal_data', models.CharField(max_length=30)),
                ('edit', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('age', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('language_preference', models.CharField(max_length=40)),
                ('account_options', models.CharField(max_length=30)),
                ('change_password', models.CharField(max_length=30)),
                ('change', models.CharField(max_length=30)),
                ('delete_account', models.CharField(max_length=30)),
                ('delete', models.CharField(max_length=30)),
                ('update_data', models.CharField(max_length=30)),
                ('cancel', models.CharField(max_length=30)),
                ('btn_save', models.CharField(max_length=30)),
                ('confirmation_message', models.CharField(max_length=255)),
            ],
        ),
    ]
